// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hajxahucnyzlzbihazse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhanhhaHVjbnl6bHpiaWhhenNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3ODc5MjYsImV4cCI6MjA4MDM2MzkyNn0.igpYyAL_rjBPwz6LnJoJZE8bgYgS-avc0TlTCCn_Zoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});